[package]
name = "wasm-pack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
serde_json = "*"
url = "2.5.4"
wasm-bindgen = "0.2"
